language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "akshya1997"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

before_install:
  - chmod +x mvnw
