language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "akshya1997"
    token:
      secure: 5a777be777aab71e27ff0a5122c3575f7c0aa9ae

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AKSHYA1997_travis

before_install:
  - chmod +x mvnw
