language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "akshya1997"
    token: $SONARCUBE_TOKEN

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AKSHYA1997_travis

before_install:
  - chmod +x mvnw
